#
# Makefile for PN512 HCI based NFC driver
#
obj-$(CONFIG_NFC_PN512)     		+= pn512.o

obj-y 		+= spi.o
obj-y  		+= iso14443_typeA.o
obj-y  		+= iso14443_typeB.o
obj-y		+= iso14444.o
obj-y     	+= picc.o
obj-y     	+= pcd.o
obj-y		+= delay.o
obj-y		+= pcd_config.o
#obj-y		+= mifare.o
#obj-y		+= felica.o
#obj-y		+= topaz.o
obj-y		+= pcsc.o

